const sampleJobs = [
  {
    id: 1,
    title: "React Developer",
    company: "ABC Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "React Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 2,
    title: "React Developer",
    company: "ABC Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "Angular Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 3,
    title: "React Developer",
    company: "XYZ Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "Vue Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 4,
    title: "React Developer",
    company: "XYZ Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "JS Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 5,
    title: "React Developer",
    company: "XYZ Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "Node Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 6,
    title: "React Developer",
    company: "DCB Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "Express Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 7,
    title: "React Developer",
    company: "DCB Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "React Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 8,
    title: "React Developer",
    company: "DCB Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "React Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 9,
    title: "React Developer",
    company: "HSA Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "React Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
  {
    id: 10,
    title: "React Developer",
    company: "HSA Company",
    location: "Tiger Market",
    phone: 9846695531,
    website: "https://pasanglama.com.np",
    requirements: "At least 2 years of experience working as React Developer",
    salary: 99999,
    vacancy: "React Developer",
    skills: [
      "Good knowledge of React core concepts",
      "Knowledge of Redux and Next Js",
    ],
    category: "IT and Tech",
    posted_date: "2080/02/28",
    "closing date": "2080/03/10",
    description: "hfiodhfoidhifhdifdsofhdohfo",
    created_by: {
      type: "sada sdas asdadad",
      ref: "User",
    },
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    ],
  },
];

export default sampleJobs;
